// Current curated collection — only files that remain in the images folder are used.
const photos=[1,2,4,7,8,9,10,11,15,18,19,20,21,23,24,25,26,28,29,30,31,32,33,34,35,36,37,38,39,40].map(number=>`images/photo_${number}_2026-10-03_21-11-33.jpg`);
const captions=['Good vibes ♡','A beautiful memory','One for the scrapbook ✦','Always a special moment','Keep smiling 🌷','This moment deserves a place here','Another little memory','Forever worth remembering'];
const grid=document.querySelector('#scrapbook-grid');
photos.forEach((src,i)=>{const f=document.createElement('figure');f.className='scrap polaroid reveal';f.style.setProperty('--rot',`${[-4,3,-2,5,1,-5,4,-1][i%8]}deg`);f.style.setProperty('--aspect',i%5===0?'1/1.25':i%3===0?'1.15/1':'1/.95');f.innerHTML=`<img loading="lazy" src="${src}" alt="Memory ${i+1} with Neha Tai"><figcaption>${captions[i%captions.length]}</figcaption><span class="heart">♡</span>`;f.tabIndex=0;f.setAttribute('role','button');f.setAttribute('aria-label',`View memory ${i+1}`);grid.append(f)});
const special=['Your Kind Heart ♡','Your Beautiful Smile 🌸','Your Way of Understanding People ✦','Your Strength 🌿','Your Positive Energy ☀','The Respect You Earn Naturally','Your Presence 🌷','Simply Being You 🎀'];
const wishes=['More smiles 😊','More adventures 🌷','More success ✦','More peaceful days 🤍','More beautiful memories 📸','More reasons to celebrate 🎀','More dreams coming true 🌟','More happiness than yesterday ♡'];
function cards(items,el,cls){items.forEach((x,i)=>{const d=document.createElement('div');d.className=`${cls} reveal`;d.style.setProperty('--rot',`${[-2,2,-1,3][i%4]}deg`);d.textContent=x;el.append(d)})}cards(special,document.querySelector('#special-cards'),'special-card');cards(wishes,document.querySelector('#wish-grid'),'wish');
const timePhotos=[2,8,14,20,26],timeLines=['Where the memories began…','A moment worth remembering…','One more reason to smile…','Another page in our little scrapbook…','Some memories deserve to stay forever…'];const tl=document.querySelector('#timeline-list');timePhotos.forEach((n,i)=>{let a=photos[n];let d=document.createElement('article');d.className='memory reveal';d.innerHTML=`<figure class="polaroid" style="--rot:${i%2?3:-3}deg"><img loading="lazy" src="${a}" alt="Timeline memory ${i+1}"><figcaption>${timeLines[i]}</figcaption></figure><p>little note — saved with warmth ♡</p>`;tl.append(d)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
const lightbox=document.querySelector('#lightbox'),lightImg=lightbox.querySelector('img'),lightCap=lightbox.querySelector('figcaption');function openPhoto(el){lightImg.src=el.querySelector('img').src;lightCap.textContent=el.querySelector('figcaption').textContent;lightbox.hidden=false;document.body.style.overflow='hidden';document.querySelector('#close-lightbox').focus()}document.querySelectorAll('.scrap').forEach(x=>{x.addEventListener('click',()=>openPhoto(x));x.addEventListener('keydown',e=>{if(e.key==='Enter')openPhoto(x)})});function closeLight(){lightbox.hidden=true;document.body.style.overflow=''}document.querySelector('#close-lightbox').onclick=closeLight;lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLight()});
const audio=document.querySelector('#birthday-audio'),music=document.querySelector('#music');const candidates=['HAPPY_BIRTHDAY_TO_YOU_PIANO_INSTRUMENTAL_BEST_HAPPY_BITHDAY_MUSIC.mp3','music/birthday.mp3','music/birthday-song.mp3','birthday.mp3'];let audioFound=false;function loadAudio(i=0){if(i>=candidates.length)return;audio.src=candidates[i];audio.oncanplay=()=>audioFound=true;audio.onerror=()=>loadAudio(i+1)}loadAudio();function toggleMusic(){if(!audioFound){music.title='Music is loading — please try again in a moment';music.classList.add('no-audio');return}if(audio.paused){audio.play();music.classList.add('playing');music.setAttribute('aria-label','Pause birthday music')}else{audio.pause();music.classList.remove('playing');music.setAttribute('aria-label','Play birthday music')}}music.onclick=toggleMusic;
document.querySelector('#enter').onclick=()=>{document.querySelector('#opening').classList.add('open');audio.play().then(()=>music.classList.add('playing')).catch(()=>{});setTimeout(()=>{document.querySelector('#opening').hidden=true;document.querySelector('#site').hidden=false;window.scrollTo(0,0)},2700)};
const overlay=document.querySelector('#surprise-overlay');document.querySelector('#surprise').onclick=()=>{overlay.hidden=false;document.body.style.overflow='hidden'};document.querySelector('#close-surprise').onclick=()=>{overlay.hidden=true;document.body.style.overflow=''};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.hidden){overlay.hidden=true;document.body.style.overflow=''}});
let stars=0;const secret=document.querySelector('#secret');function hitStar(){stars++;if(stars===3){secret.hidden=false;setTimeout(()=>secret.hidden=true,5500);stars=0}}document.querySelector('#secret-star').addEventListener('click',hitStar);document.querySelector('#secret-star').addEventListener('keydown',e=>{if(e.key==='Enter')hitStar()});
const dot=document.querySelector('.cursor-dot');addEventListener('mousemove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px'});document.querySelectorAll('button,.scrap').forEach(x=>x.addEventListener('mouseenter',()=>{dot.style.width='22px';dot.style.height='22px'}));document.querySelectorAll('button,.scrap').forEach(x=>x.addEventListener('mouseleave',()=>{dot.style.width='12px';dot.style.height='12px'}));
